version: 2
jobs:
    test:
        docker:
          - image: circleci/node:8.10
        filters:
            branches:
                only: master
        steps:
          - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

        - run: yarn install

        - save_cache:
            paths:
            - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run: yarn lint
workflows:
  version: 2
  test:
    jobs:
      - test
